version: '3.9'

services:
  api:
    image: ${IMAGE}
    container_name: stosyst-server
    restart: always
    env_file:
      - .backend.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - stosyst-network

  client:
    image: ${IMAGE}
    container_name: stosyst-client
    restart: always
    env_file:
      - .client.env
    ports:
      - "80:80"
    networks:
      - stosyst-network

  mongo:
    image: mongo:6.0
    container_name: stosyst-db
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - stosyst-network

volumes:
  mongo_data:

networks:
  mern-network:
    driver: bridge
