services:
  mongo:
    image: mongo:7
    container_name: stosyst-db
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - stosyst-network

  api:
    image: ${IMAGE}   # 👈 passed from .env (your CI writes IMAGE=...)
    container_name: stosyst-api
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - stosyst-network

  client:
    image: shehuzaks/stosyst-client:latest  # 👈 or pass via env if you want
    container_name: stosyst-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - stosyst-network

volumes:
  mongo_data:

networks:
  stosyst-network:
    driver: bridge
