version: '3.9'

services:
  backend:
    image: code2013/mern-backend:latest
    container_name: mern-backend
    restart: always
    env_file:
      - .backend.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mern-network

  frontend:
    image: code2013/mern-frontend:latest
    container_name: mern-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - mern-network

  mongo:
    image: mongo:6.0
    container_name: mern-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-network

volumes:
  mongo_data:

networks:
  mern-network:
    driver: bridge
