name: Deploy to Production

on:
  repository_dispatch:
    types: [deploy-client, deploy-server]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/mern-deployment

            # Pull latest deployment repo changes
            git pull origin main

            # Update image reference from dispatched event
            echo "IMAGE=${{ github.event.client_payload.image }}" > .env

            # Authenticate with Docker Hub (needed for private client image)
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            # Pull latest images
            docker compose -f docker-compose.prod.yml pull

            # Restart services
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
